### ISSUE TITLE
paleomix doesnot work

### ISSUE THREAD

**Issue by xuefenfei712** [MikkelSchubert/paleomix#24]
I have installed paleomix, and run the example, for a few days, but no result. we refer to top, it accounts for ZERO CPU.
only like this ...
Reading makefiles ...
  - Validating prefixes ...

![image](https://user-images.githubusercontent.com/58972242/70977091-2ac0c780-20e8-11ea-95c8-fd0e605492e0.png)
Your kind reply will be more helpful for me, thankyou!

**Comment by MikkelSchubert** [comment]
PALEOMIX definitely should not take that long to validate prefixes, as that just involves a bit of file IO. I'd expect a few seconds normally and maybe a couple of minutes if one of them needs to be indexed. 

Are your FASTA files by any chance located on a network drive that was not properly connected? That is the only case I can currently think of that could cause it to hang like this.

If it is still running, or if it happens when you run it, then please try to press Ctrl+C and copy/paste the output here. It should give us a clue as to where the program got stuck. 

Best,
 Mikkel

**Comment by xuefenfei712** [comment]
Thanyou for your reply, I just use the example data you provided, and reference is rCRS.fasta, also indexed well (see blow picture1), and this time I use "paleomix bam_pipeline dryrun 000_makefile.yaml" also get the same problem. Sorry for that, my friends (Clio) and I don't know how to solve it.
![image](https://user-images.githubusercontent.com/58972242/71173501-dbbc9300-229d-11ea-8e20-385e8a9f5f27.png)

**Comment by MikkelSchubert** [comment]
This definitely should not happen, but I cannot find any obvious reasons why your copy of PALEOMIX would lock up in this manner.

You say that you are able to trigger the same problem using "paleomix bam_pipeline dryrun 000_makefile.yaml", but what happens if you kill the process using CTRL+C? Are you able to do that and does Python print a traceback upon being killed? If possible, try to paste that traceback here, as it may include information about the cause of this problem.

Best,
Mikkel

**Comment by xuefenfei712** [comment]
Thankyou for your reply, I type ctrl+c and get the below result
^CTraceback (most recent call last):
  File "/home/user/anaconda3/envs/python27/bin/paleomix", line 11, in <module>
    load_entry_point('paleomix==1.2.14', 'console_scripts', 'paleomix')()
  File "/home/user/anaconda3/envs/python27/lib/python2.7/site-packages/paleomix/__init__.py", line 38, in run
    return paleomix.main.main(argv)
  File "/home/user/anaconda3/envs/python27/lib/python2.7/site-packages/paleomix/main.py", line 235, in main
    return module.main(argv[1:])
  File "/home/user/anaconda3/envs/python27/lib/python2.7/site-packages/paleomix/tools/bam_pipeline/pipeline.py", line 319, in main
    return run(config, args[1:], pipeline_variant=pipeline)
  File "/home/user/anaconda3/envs/python27/lib/python2.7/site-packages/paleomix/tools/bam_pipeline/pipeline.py", line 213, in run
    index_references(config, makefiles)
  File "/home/user/anaconda3/envs/python27/lib/python2.7/site-packages/paleomix/tools/bam_pipeline/pipeline.py", line 157, in index_references
    dependencies=(valid_node,))
  File "/home/user/anaconda3/envs/python27/lib/python2.7/site-packages/paleomix/nodes/picard.py", line 106, in __init__
    builder = picard_command(config, "CreateSequenceDictionary")
  File "/home/user/anaconda3/envs/python27/lib/python2.7/site-packages/paleomix/nodes/picard.py", line 253, in picard_command
    jre_options=config.jre_options)
  File "/home/user/anaconda3/envs/python27/lib/python2.7/site-packages/paleomix/atomiccmd/builder.py", line 366, in __init__
    close_fds=True)
  File "/home/user/anaconda3/envs/python27/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/user/anaconda3/envs/python27/lib/python2.7/subprocess.py", line 1073, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/home/user/anaconda3/envs/python27/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
I used anaconda to install paleomix, also python work well in my server.
Thankyou!
X

**Comment by MikkelSchubert** [comment]
The problem seems to happen when Paleomix tries to check if the version of java that is installed.

The command that Paleomix tries to run is something close to the following:

       java -server -Djava.awt.headless=true -XX:+UseSerialGC -d64 -version

Try to run that command directly on your server and see what happens.

**Comment by xuefenfei712** [comment]
after running your code, and get the result:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
However, also not working now.....
I also reinstalled paleomix, Adapteremoval and the result like before.
Thankyou more!

**Comment by MikkelSchubert** [comment]
That is strange.

Can you try the following and tell me what happens (does Paleomix still get
stuck?):

1. Run paleomix with the option "--jre-option=-Xmx4g". That should skip the
check where Paleomix seems to get stuck:

    $ paleomix bam_pipeline run --jre-option=-Xmx4g 000_makefile.yaml

2. Run paleomix with the option "--temp-root":

    $ paleomix bam_pipeline run --temp-root ./temp/ 000_makefile.yaml

Best regards,
 Mikkel

**Comment by MikkelSchubert** [comment]
Closing due to lack of activity.
Feel free to open a new issue if you still have this problem
