### ISSUE TITLE
'empty header' error

### ISSUE THREAD

**Issue by beeso018** [MikkelSchubert/paleomix#5]
Having problems with pysam I think... Any ideas about what's going on here?

```
Traceback (most recent call last):
  File "/panfs/roc/groups/3/mccuem/beesons/WGS/paleomix/bin/paleomix", line 250, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/panfs/roc/groups/3/mccuem/beesons/WGS/paleomix/bin/paleomix", line 246, in main
    return module.main(argv)
  File "/home/mccuem/beesons/.local/lib/python2.7/site-packages/pypeline/tools/cleanup.py", line 313, in main
    return _pipe_to_bam()
  File "/home/mccuem/beesons/.local/lib/python2.7/site-packages/pypeline/tools/cleanup.py", line 85, in _pipe_to_bam
    with pysam.Samfile("-", "r") as input_handle:
  File "pysam/calignmentfile.pyx", line 311, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4929)
  File "pysam/calignmentfile.pyx", line 510, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7138)
ValueError: file header is empty (mode='r') - is it SAM/BAM format?
```

**Comment by MikkelSchubert** [comment]
Did this error result from running the pipeline?

If so, can you include the pipe* files from the failed task?
This error is likely just the result of some other part of that task failing.

Cheers.

**Comment by beeso018** [comment]
Here is the whole temporary directory:

https://drive.google.com/file/d/0B4jvMTKwOo79OXZsbW9zSFp1ek0/view?usp=sharing

**Comment by MikkelSchubert** [comment]
That's a bit excessive; I only needed the pipe* logfiles (< 1mb in total), not the full temp folder.
However, assuming that bam_pipeline.20150803_152327_00.log is the log for your latest run, it looks like one of the BWA instances was SIGKILL'd (and the rest of the programs appear to have been SIGTERM'd by the pipeline).

Are you running the pipeline on a system with runtime or memory limits imposed, or simply with limited memory? If so, an instance of BWA may have been killed because this. Note that you'll need something like 12+ GB of RAM for a genome the size of the human genome, since the pipeline runs BWA aln / sampe in parallel.

**Comment by beeso018** [comment]
Yes, looks like memory is the problem here then since it's through a queue system and I have to request memory and walltime when I submit a job. I will try requesting >12GB and see if that solves the issue. Thanks!
